set -x
cd app

export REACT_APP_VERSION=${VERSION}
export REACT_APP_HOSTNAME=${HOSTNAME}
export REACT_APP_KUBERNETES_SERVICE_HOST=${KUBERNETES_SERVICE_HOST}
export REACT_APP_KUBERNETES_NAMESPACE=${KUBERNETES_NAMESPACE}

yarn start