apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/rewrite-target: /
      ingress.kubernetes.io/force-ssl-redirect: true
      kubernetes.io/ingress.class: external-ingress
      monitor.stakater.com/enabled: true
    fabric8.io/ingress.path: /api/hello-kubernetes/
  labels:
    app: hello-kubernetes
    expose: "true"
  name: hello-kubernetes
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello-kubernetes
  type: ClusterIP
